In [84]:
import pandas as pd
import numpy as np

In [85]:
sf_permits = pd.read_csv("../dataset/building-permit-applications-data/Building_Permits.csv")

/home/neil/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [87]:
sf_pemits2 = sf_permits.drop(columns=['Permit Number','Permit Type Definition','Block','Lot','Street Number','Street Number Suffix','Street Name','Street Suffix','Unit','Unit Suffix','Description','Structural Notification','Number of Existing Stories','Number of Proposed Stories','Voluntary Soft-Story Retrofit','Fire Only Permit','Existing Use','Existing Units','Proposed Use','Proposed Units','Plansets','TIDF Compliance','Existing Construction Type','Existing Construction Type Description','Proposed Construction Type','Proposed Construction Type Description','Site Permit','Neighborhoods - Analysis Boundaries','Location','Record ID'])

In [88]:
sf_pemits2

,Permit Type,Permit Creation Date,Current Status,Current Status Date,Filed Date,Issued Date,Completed Date,First Construction Document Date,Permit Expiration Date,Estimated Cost,Revised Cost,Supervisor District,Zipcode
0,4,05/06/2015,expired,12/21/2017,05/06/2015,11/09/2015,NaN,11/09/2015,11/03/2016,4000.00,4000.00,3.0,94102.0
1,4,04/19/2016,issued,08/03/2017,04/19/2016,08/03/2017,NaN,08/03/2017,12/03/2017,1.00,500.00,3.0,94102.0
2,3,05/27/2016,withdrawn,09/26/2017,05/27/2016,NaN,NaN,NaN,NaN,20000.00,NaN,3.0,94109.0
3,8,11/07/2016,complete,07/24/2017,11/07/2016,07/18/2017,07/24/2017,07/18/2017,07/13/2018,2000.00,2000.00,3.0,94109.0
4,6,11/28/2016,issued,12/01/2017,11/28/2016,12/01/2017,NaN,11/20/2017,12/01/2018,100000.00,100000.00,6.0,94102.0
5,8,06/14/2017,issued,07/06/2017,06/14/2017,07/06/2017,NaN,07/06/2017,07/01/2018,4000.00,4000.00,10.0,94107.0
6,8,06/30/2017,complete,07/12/2017,06/30/2017,06/30/2017,07/12/2017,06/30/2017,06/25/2018,12000.00,12000.00,5.0,94122.0
7,8,06/30/2017,issued,06/30/2017,06/30/2017,06/30/2017,NaN,06/30/2017,NaN,NaN,0.00,10.0,94124.0
8,8,07/05/2017,issued,07/05/2017,07/05/2017,07/05/2017,NaN,07/05/2017,NaN,NaN,1.00,5.0,94117.0
9,8,07/06/2017,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,0.00,8.0,94117.0
10,8,07/06/2017,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,1.00,8.0,94114.0
11,8,07/07/2017,issued,07/07/2017,07/07/2017,07/07/2017,NaN,07/07/2017,NaN,NaN,1.00,5.0,94102.0
12,8,07/10/2017,issued,07/10/2017,07/10/2017,07/10/2017,NaN,07/10/2017,NaN,NaN,1.00,8.0,94114.0
13,8,07/25/2017,filed,07/25/2017,07/25/2017,NaN,NaN,NaN,NaN,30000.00,0.00,8.0,94131.0
14,8,07/26/2017,issued,07/26/2017,07/26/2017,07/26/2017,NaN,07/26/2017,NaN,NaN,1.00,2.0,94115.0
15,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,3.0,94108.0
16,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,3.0,94104.0
17,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,8.0,94114.0
18,8,07/28/2017,filed,07/28/2017,07/28/2017,NaN,NaN,NaN,NaN,75000.00,0.00,2.0,94123.0
19,8,07/28/2017,issued,07/28/2017,07/28/2017,07/28/2017,NaN,07/28/2017,NaN,NaN,1.00,8.0,94114.0
20,8,07/31/2017,issued,07/31/2017,07/31/2017,07/31/2017,NaN,07/31/2017,NaN,NaN,1.00,5.0,94117.0
21,8,08/01/2017,filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,100000.00,0.00,9.0,94110.0
22,3,08/01/2017,filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,100000.00,NaN,3.0,94133.0
23,8,08/07/2017,issued,08/07/2017,08/07/2017,08/07/2017,NaN,08/07/2017,NaN,NaN,1.00,2.0,94123.0
24,8,08/08/2017,issued,08/08/2017,08/08/2017,08/08/2017,NaN,08/08/2017,08/08/2018,64650.00,64650.00,2.0,94123.0
25,8,08/16/2017,issued,08/16/2017,08/16/2017,08/16/2017,NaN,08/16/2017,02/16/2018,7000.00,7000.00,4.0,94122.0
26,8,08/18/2017,issued,08/18/2017,08/18/2017,08/18/2017,NaN,08/18/2017,NaN,NaN,1.00,1.0,94121.0
27,8,08/21/2017,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,1.00,5.0,94117.0
28,8,08/21/2017,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,1.00,7.0,94122.0
29,8,08/22/2017,issued,08/22/2017,08/22/2017,08/22/2017,NaN,08/22/2017,NaN,NaN,1.00,3.0,94102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,2.0,94109.0
198871,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,5.0,94117.0
198872,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,10000.00,0.00,8.0,94114.0
198873,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1.00,1.00,9.0,94110.0
198874,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018,10000.00,15000.00,8.0,94131.0
198875,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,1.00,0.00,5.0,94102.0
198876,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,0.00,5.0,94117.0
198877,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1000.00,1000.00,11.0,94112.0
198878,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,20000.00,0.00,9.0,94110.0
198879,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018,18453.12,18453.12,11.0,94112.0
198880,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,7.0,94122.0
198881,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,3.0,94133.0
198882,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1.00,1.00,11.0,94112.0
198883,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,3.0,94102.0
198884,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,NaN,1.00,6.0,94103.0
198885,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,5000.00,0.00,4.0,94116.0
198886,3,09/06/2017,approved,01/11/2018,09/06/2017,NaN,NaN,NaN,NaN,65000.00,65000.00,NaN,NaN
198887,8,10/04/2017,complete,12/06/2017,10/04/2017,11/03/2017,12/06/2017,11/03/2017,11/03/2018,30000.00,30000.00,NaN,NaN
198888,8,10/11/2017,complete,12/07/2017,10/11/2017,10/12/2017,12/07/2017,10/12/2017,10/12/2018,18000.00,30000.00,NaN,NaN
198889,8,10/24/2017,complete,12/05/2017,10/24/2017,10/24/2017,12/05/2017,10/24/2017,04/24/2018,20000.00,20000.00,NaN,NaN
198890,3,11/27/2017,filed,11/27/2017,11/27/2017,NaN,NaN,NaN,NaN,750000.00,750000.00,NaN,NaN
198891,8,11/27/2017,issued,12/08/2017,11/27/2017,12/08/2017,NaN,12/08/2017,04/08/2018,1.00,1.00,NaN,NaN
198892,8,12/04/2017,issued,01/16/2018,12/04/2017,01/16/2018,NaN,01/16/2018,01/16/2019,55000.00,38000.00,NaN,NaN
198893,8,12/05/2017,complete,01/22/2018,12/05/2017,12/05/2017,01/22/2018,12/05/2017,04/05/2018,2800.00,2800.00,NaN,NaN
198894,8,12/05/2017,issued,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,06/05/2018,7400.00,7400.00,NaN,NaN
198895,8,12/05/2017,issued,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,NaN,NaN,1.00,NaN,NaN
198896,8,12/05/2017,issued,12/06/2017,12/05/2017,12/06/2017,NaN,12/06/2017,04/06/2018,5000.00,5000.00,NaN,NaN
198897,8,12/06/2017,issued,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN,NaN,1.00,NaN,NaN
198898,8,12/06/2017,issued,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN,NaN,1.00,NaN,NaN
198899,8,12/07/2017,issued,12/07/2017,12/07/2017,12/07/2017,NaN,12/07/2017,NaN,NaN,1.00,NaN,NaN

In [89]:
sf_pemits2['Current Status']

0           expired
1            issued
2         withdrawn
3          complete
4            issued
5            issued
6          complete
7            issued
8            issued
9            issued
10           issued
11           issued
12           issued
13            filed
14           issued
15           issued
16           issued
17           issued
18            filed
19           issued
20           issued
21            filed
22            filed
23           issued
24           issued
25           issued
26           issued
27           issued
28           issued
29           issued
            ...
198870       issued
198871       issued
198872        filed
198873       issued
198874       issued
198875        filed
198876       issued
198877       issued
198878        filed
198879       issued
198880       issued
198881       issued
198882       issued
198883       issued
198884        filed
198885        filed
198886     approved
198887     complete
198888     complete
198889     complete
198890        filed
198891       issued
198892       issued
198893     complete
198894       issued
198895       issued
198896       issued
198897       issued
198898       issued
198899       issued
Name: Current Status, Length: 198900, dtype: object

In [90]:
df2 = sf_pemits2.loc[sf_pemits2['Current Status'].isin(['issued','complete'])]

In [91]:
df2['Current Status']

1           issued
3         complete
4           issued
5           issued
6         complete
7           issued
8           issued
9           issued
10          issued
11          issued
12          issued
14          issued
15          issued
16          issued
17          issued
19          issued
20          issued
23          issued
24          issued
25          issued
26          issued
27          issued
28          issued
29          issued
30          issued
31          issued
32          issued
34          issued
35          issued
36          issued
            ...
198858      issued
198861      issued
198863      issued
198865      issued
198867      issued
198868      issued
198869      issued
198870      issued
198871      issued
198873      issued
198874      issued
198876      issued
198877      issued
198879      issued
198880      issued
198881      issued
198882      issued
198883      issued
198887    complete
198888    complete
198889    complete
198891      issued
198892      issued
198893    complete
198894      issued
198895      issued
198896      issued
198897      issued
198898      issued
198899      issued
Name: Current Status, Length: 180636, dtype: object

In [92]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180636 entries, 1 to 198899
Data columns (total 13 columns):
Permit Type                         180636 non-null int64
Permit Creation Date                180636 non-null object
Current Status                      180636 non-null object
Current Status Date                 180636 non-null object
Filed Date                          180636 non-null object
Issued Date                         180618 non-null object
Completed Date                      97130 non-null object
First Construction Document Date    180587 non-null object
Permit Expiration Date              143748 non-null object
Estimated Cost                      143662 non-null float64
Revised Cost                        180625 non-null float64
Supervisor District                 178999 non-null float64
Zipcode                             179000 non-null float64
dtypes: float64(4), int64(1), object(8)
memory usage: 24.3+ MB

In [93]:
missing = df2.isnull().sum()

In [94]:
missing

Permit Type                             0
Permit Creation Date                    0
Current Status                          0
Current Status Date                     0
Filed Date                              0
Issued Date                            18
Completed Date                      83506
First Construction Document Date       49
Permit Expiration Date              36888
Estimated Cost                      36974
Revised Cost                           11
Supervisor District                  1637
Zipcode                              1636
dtype: int64

In [95]:
df3 = df2.drop(columns=['Completed Date','Permit Expiration Date','Estimated Cost'])

In [96]:
missing2 = df3.isnull().sum()

In [97]:
missing2

Permit Type                            0
Permit Creation Date                   0
Current Status                         0
Current Status Date                    0
Filed Date                             0
Issued Date                           18
First Construction Document Date      49
Revised Cost                          11
Supervisor District                 1637
Zipcode                             1636
dtype: int64

In [98]:
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [99]:
reg=linear_model.LinearRegression()

In [100]:
df4 = df3[pd.notnull(df3['Issued Date'])]

In [101]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180618 entries, 1 to 198899
Data columns (total 10 columns):
Permit Type                         180618 non-null int64
Permit Creation Date                180618 non-null object
Current Status                      180618 non-null object
Current Status Date                 180618 non-null object
Filed Date                          180618 non-null object
Issued Date                         180618 non-null object
First Construction Document Date    180586 non-null object
Revised Cost                        180609 non-null float64
Supervisor District                 178981 non-null float64
Zipcode                             178982 non-null float64
dtypes: float64(3), int64(1), object(6)
memory usage: 15.2+ MB

In [103]:
#import time
#import datetime
#df4['Permit Creation Date22'] = time.mktime(datetime.datetime.strptime(df4['Permit Creation Date'], "%m%d%Y").timetuple())

In [104]:
import datetime as dt
df4['Permit Creation Date'] = pd.to_datetime(df4['Permit Creation Date'])
df4['Permit Creation Date66']=df4['Permit Creation Date'].map(dt.datetime.toordinal)

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [105]:
df4['Permit Creation Date66']

1         736073
3         736275
4         736296
5         736494
6         736510
7         736510
8         736515
9         736516
10        736516
11        736517
12        736520
14        736536
15        736537
16        736537
17        736537
19        736538
20        736541
23        736548
24        736549
25        736557
26        736559
27        736562
28        736562
29        736563
30        736564
31        736564
32        736564
34        736566
35        736566
36        736569
           ...
198858    736748
198861    736748
198863    736748
198865    736748
198867    736748
198868    736748
198869    736748
198870    736748
198871    736748
198873    736748
198874    736748
198876    736748
198877    736748
198879    736748
198880    736748
198881    736748
198882    736748
198883    736748
198887    736606
198888    736613
198889    736626
198891    736660
198892    736667
198893    736668
198894    736668
198895    736668
198896    736668
198897    736669
198898    736669
198899    736670
Name: Permit Creation Date66, Length: 180618, dtype: int64

In [106]:
status = pd.Series(np.where(df4['Current Status']=='issued',1,0),name='Current Status')

In [107]:
status

0         1
1         0
2         1
3         1
4         0
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
         ..
180588    1
180589    1
180590    1
180591    1
180592    1
180593    1
180594    1
180595    1
180596    1
180597    1
180598    1
180599    1
180600    1
180601    1
180602    1
180603    1
180604    1
180605    1
180606    0
180607    0
180608    0
180609    1
180610    1
180611    0
180612    1
180613    1
180614    1
180615    1
180616    1
180617    1
Name: Current Status, Length: 180618, dtype: int64

In [108]:
import datetime as dt
df4['Current Status Date'] = pd.to_datetime(df4['Current Status Date'])
df4['Current Status Date66']=df4['Current Status Date'].map(dt.datetime.toordinal)

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [109]:
df4['Current Status Date66']

1         736544
3         736534
4         736664
5         736516
6         736522
7         736510
8         736515
9         736516
10        736516
11        736517
12        736520
14        736536
15        736537
16        736537
17        736537
19        736538
20        736541
23        736548
24        736549
25        736557
26        736559
27        736562
28        736562
29        736563
30        736564
31        736564
32        736564
34        736566
35        736566
36        736569
           ...
198858    736748
198861    736748
198863    736748
198865    736748
198867    736748
198868    736748
198869    736748
198870    736748
198871    736748
198873    736748
198874    736748
198876    736748
198877    736748
198879    736748
198880    736748
198881    736748
198882    736748
198883    736748
198887    736669
198888    736670
198889    736668
198891    736671
198892    736710
198893    736716
198894    736668
198895    736668
198896    736669
198897    736669
198898    736669
198899    736670
Name: Current Status Date66, Length: 180618, dtype: int64

In [110]:
df4['Filed Date'] = pd.to_datetime(df4['Filed Date'])
df4['Filed Date66']=df4['Filed Date'].map(dt.datetime.toordinal)

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [111]:
df4['Filed Date66']

1         736073
3         736275
4         736296
5         736494
6         736510
7         736510
8         736515
9         736516
10        736516
11        736517
12        736520
14        736536
15        736537
16        736537
17        736537
19        736538
20        736541
23        736548
24        736549
25        736557
26        736559
27        736562
28        736562
29        736563
30        736564
31        736564
32        736564
34        736566
35        736566
36        736569
           ...
198858    736748
198861    736748
198863    736748
198865    736748
198867    736748
198868    736748
198869    736748
198870    736748
198871    736748
198873    736748
198874    736748
198876    736748
198877    736748
198879    736748
198880    736748
198881    736748
198882    736748
198883    736748
198887    736606
198888    736613
198889    736626
198891    736660
198892    736667
198893    736668
198894    736668
198895    736668
198896    736668
198897    736669
198898    736669
198899    736670
Name: Filed Date66, Length: 180618, dtype: int64

In [112]:
df4['Issued Date'] = pd.to_datetime(df4['Issued Date'])
df4['Issued Date66']=df4['Issued Date'].map(dt.datetime.toordinal)

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [113]:
df4['Issued Date66']

1         736544
3         736528
4         736664
5         736516
6         736510
7         736510
8         736515
9         736516
10        736516
11        736517
12        736520
14        736536
15        736537
16        736537
17        736537
19        736538
20        736541
23        736548
24        736549
25        736557
26        736559
27        736562
28        736562
29        736563
30        736564
31        736564
32        736564
34        736566
35        736566
36        736569
           ...
198858    736748
198861    736748
198863    736748
198865    736748
198867    736748
198868    736748
198869    736748
198870    736748
198871    736748
198873    736748
198874    736748
198876    736748
198877    736748
198879    736748
198880    736748
198881    736748
198882    736748
198883    736748
198887    736636
198888    736614
198889    736626
198891    736671
198892    736710
198893    736668
198894    736668
198895    736668
198896    736669
198897    736669
198898    736669
198899    736670
Name: Issued Date66, Length: 180618, dtype: int64

In [116]:
df5 = df4

In [117]:
df5

,Permit Type,Permit Creation Date,Current Status,Current Status Date,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,Zipcode,Permit Creation Date66,Current Status Date66,Filed Date66,Issued Date66
1,4,2016-04-19,issued,2017-08-03,2016-04-19,2017-08-03,08/03/2017,500.00,3.0,94102.0,736073,736544,736073,736544
3,8,2016-11-07,complete,2017-07-24,2016-11-07,2017-07-18,07/18/2017,2000.00,3.0,94109.0,736275,736534,736275,736528
4,6,2016-11-28,issued,2017-12-01,2016-11-28,2017-12-01,11/20/2017,100000.00,6.0,94102.0,736296,736664,736296,736664
5,8,2017-06-14,issued,2017-07-06,2017-06-14,2017-07-06,07/06/2017,4000.00,10.0,94107.0,736494,736516,736494,736516
6,8,2017-06-30,complete,2017-07-12,2017-06-30,2017-06-30,06/30/2017,12000.00,5.0,94122.0,736510,736522,736510,736510
7,8,2017-06-30,issued,2017-06-30,2017-06-30,2017-06-30,06/30/2017,0.00,10.0,94124.0,736510,736510,736510,736510
8,8,2017-07-05,issued,2017-07-05,2017-07-05,2017-07-05,07/05/2017,1.00,5.0,94117.0,736515,736515,736515,736515
9,8,2017-07-06,issued,2017-07-06,2017-07-06,2017-07-06,07/06/2017,0.00,8.0,94117.0,736516,736516,736516,736516
10,8,2017-07-06,issued,2017-07-06,2017-07-06,2017-07-06,07/06/2017,1.00,8.0,94114.0,736516,736516,736516,736516
11,8,2017-07-07,issued,2017-07-07,2017-07-07,2017-07-07,07/07/2017,1.00,5.0,94102.0,736517,736517,736517,736517
12,8,2017-07-10,issued,2017-07-10,2017-07-10,2017-07-10,07/10/2017,1.00,8.0,94114.0,736520,736520,736520,736520
14,8,2017-07-26,issued,2017-07-26,2017-07-26,2017-07-26,07/26/2017,1.00,2.0,94115.0,736536,736536,736536,736536
15,8,2017-07-27,issued,2017-07-27,2017-07-27,2017-07-27,07/27/2017,1.00,3.0,94108.0,736537,736537,736537,736537
16,8,2017-07-27,issued,2017-07-27,2017-07-27,2017-07-27,07/27/2017,1.00,3.0,94104.0,736537,736537,736537,736537
17,8,2017-07-27,issued,2017-07-27,2017-07-27,2017-07-27,07/27/2017,1.00,8.0,94114.0,736537,736537,736537,736537
19,8,2017-07-28,issued,2017-07-28,2017-07-28,2017-07-28,07/28/2017,1.00,8.0,94114.0,736538,736538,736538,736538
20,8,2017-07-31,issued,2017-07-31,2017-07-31,2017-07-31,07/31/2017,1.00,5.0,94117.0,736541,736541,736541,736541
23,8,2017-08-07,issued,2017-08-07,2017-08-07,2017-08-07,08/07/2017,1.00,2.0,94123.0,736548,736548,736548,736548
24,8,2017-08-08,issued,2017-08-08,2017-08-08,2017-08-08,08/08/2017,64650.00,2.0,94123.0,736549,736549,736549,736549
25,8,2017-08-16,issued,2017-08-16,2017-08-16,2017-08-16,08/16/2017,7000.00,4.0,94122.0,736557,736557,736557,736557
26,8,2017-08-18,issued,2017-08-18,2017-08-18,2017-08-18,08/18/2017,1.00,1.0,94121.0,736559,736559,736559,736559
27,8,2017-08-21,issued,2017-08-21,2017-08-21,2017-08-21,08/21/2017,1.00,5.0,94117.0,736562,736562,736562,736562
28,8,2017-08-21,issued,2017-08-21,2017-08-21,2017-08-21,08/21/2017,1.00,7.0,94122.0,736562,736562,736562,736562
29,8,2017-08-22,issued,2017-08-22,2017-08-22,2017-08-22,08/22/2017,1.00,3.0,94102.0,736563,736563,736563,736563
30,8,2017-08-23,issued,2017-08-23,2017-08-23,2017-08-23,08/23/2017,1.00,3.0,94133.0,736564,736564,736564,736564
31,8,2017-08-23,issued,2017-08-23,2017-08-23,2017-08-23,08/23/2017,1.00,8.0,94114.0,736564,736564,736564,736564
32,8,2017-08-23,issued,2017-08-23,2017-08-23,2017-08-23,08/23/2017,0.00,9.0,94110.0,736564,736564,736564,736564
34,8,2017-08-25,issued,2017-08-25,2017-08-25,2017-08-25,08/25/2017,1.00,8.0,94103.0,736566,736566,736566,736566
35,8,2017-08-25,issued,2017-08-25,2017-08-25,2017-08-25,08/25/2017,1.00,5.0,94115.0,736566,736566,736566,736566
36,8,2017-08-28,issued,2017-08-28,2017-08-28,2017-08-28,08/28/2017,1.00,8.0,94114.0,736569,736569,736569,736569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198858,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,0.00,2.0,94115.0,736748,736748,736748,736748
198861,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,3.0,94108.0,736748,736748,736748,736748
198863,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,45000.00,5.0,94117.0,736748,736748,736748,736748
198865,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,2.0,94118.0,736748,736748,736748,736748
198867,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,10.0,94107.0,736748,736748,736748,736748
198868,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,9.0,94110.0,736748,736748,736748,736748
198869,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,2.0,94109.0,736748,736748,736748,736748
198870,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,2.0,94109.0,736748,736748,736748,736748
198871,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,5.0,94117.0,736748,736748,736748,736748
198873,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,9.0,94110.0,736748,736748,736748,736748
198874,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,15000.00,8.0,94131.0,736748,736748,736748,736748
198876,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,0.00,5.0,94117.0,736748,736748,736748,736748
198877,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1000.00,11.0,94112.0,736748,736748,736748,736748
198879,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,18453.12,11.0,94112.0,736748,736748,736748,736748
198880,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,7.0,94122.0,736748,736748,736748,736748
198881,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,3.0,94133.0,736748,736748,736748,736748
198882,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,11.0,94112.0,736748,736748,736748,736748
198883,8,2018-02-23,issued,2018-02-23,2018-02-23,2018-02-23,02/23/2018,1.00,3.0,94102.0,736748,736748,736748,736748
198887,8,2017-10-04,complete,2017-12-06,2017-10-04,2017-11-03,11/03/2017,30000.00,NaN,NaN,736606,736669,736606,736636
198888,8,2017-10-11,complete,2017-12-07,2017-10-11,2017-10-12,10/12/2017,30000.00,NaN,NaN,736613,736670,736613,736614
198889,8,2017-10-24,complete,2017-12-05,2017-10-24,2017-10-24,10/24/2017,20000.00,NaN,NaN,736626,736668,736626,736626
198891,8,2017-11-27,issued,2017-12-08,2017-11-27,2017-12-08,12/08/2017,1.00,NaN,NaN,736660,736671,736660,736671
198892,8,2017-12-04,issued,2018-01-16,2017-12-04,2018-01-16,01/16/2018,38000.00,NaN,NaN,736667,736710,736667,736710
198893,8,2017-12-05,complete,2018-01-22,2017-12-05,2017-12-05,12/05/2017,2800.00,NaN,NaN,736668,736716,736668,736668
198894,8,2017-12-05,issued,2017-12-05,2017-12-05,2017-12-05,12/05/2017,7400.00,NaN,NaN,736668,736668,736668,736668
198895,8,2017-12-05,issued,2017-12-05,2017-12-05,2017-12-05,12/05/2017,1.00,NaN,NaN,736668,736668,736668,736668
198896,8,2017-12-05,issued,2017-12-06,2017-12-05,2017-12-06,12/06/2017,5000.00,NaN,NaN,736668,736669,736668,736669
198897,8,2017-12-06,issued,2017-12-06,2017-12-06,2017-12-06,12/06/2017,1.00,NaN,NaN,736669,736669,736669,736669
198898,8,2017-12-06,issued,2017-12-06,2017-12-06,2017-12-06,12/06/2017,1.00,NaN,NaN,736669,736669,736669,736669
198899,8,2017-12-07,issued,2017-12-07,2017-12-07,2017-12-07,12/07/2017,1.00,NaN,NaN,736670,736670,736670,736670

In [118]:
df5 = df5.drop(columns=['Current Status','First Construction Document Date','Permit Creation Date','Current Status Date','Filed Date','Issued Date'])

In [119]:
df5

,Permit Type,Revised Cost,Supervisor District,Zipcode,Permit Creation Date66,Current Status Date66,Filed Date66,Issued Date66
1,4,500.00,3.0,94102.0,736073,736544,736073,736544
3,8,2000.00,3.0,94109.0,736275,736534,736275,736528
4,6,100000.00,6.0,94102.0,736296,736664,736296,736664
5,8,4000.00,10.0,94107.0,736494,736516,736494,736516
6,8,12000.00,5.0,94122.0,736510,736522,736510,736510
7,8,0.00,10.0,94124.0,736510,736510,736510,736510
8,8,1.00,5.0,94117.0,736515,736515,736515,736515
9,8,0.00,8.0,94117.0,736516,736516,736516,736516
10,8,1.00,8.0,94114.0,736516,736516,736516,736516
11,8,1.00,5.0,94102.0,736517,736517,736517,736517
12,8,1.00,8.0,94114.0,736520,736520,736520,736520
14,8,1.00,2.0,94115.0,736536,736536,736536,736536
15,8,1.00,3.0,94108.0,736537,736537,736537,736537
16,8,1.00,3.0,94104.0,736537,736537,736537,736537
17,8,1.00,8.0,94114.0,736537,736537,736537,736537
19,8,1.00,8.0,94114.0,736538,736538,736538,736538
20,8,1.00,5.0,94117.0,736541,736541,736541,736541
23,8,1.00,2.0,94123.0,736548,736548,736548,736548
24,8,64650.00,2.0,94123.0,736549,736549,736549,736549
25,8,7000.00,4.0,94122.0,736557,736557,736557,736557
26,8,1.00,1.0,94121.0,736559,736559,736559,736559
27,8,1.00,5.0,94117.0,736562,736562,736562,736562
28,8,1.00,7.0,94122.0,736562,736562,736562,736562
29,8,1.00,3.0,94102.0,736563,736563,736563,736563
30,8,1.00,3.0,94133.0,736564,736564,736564,736564
31,8,1.00,8.0,94114.0,736564,736564,736564,736564
32,8,0.00,9.0,94110.0,736564,736564,736564,736564
34,8,1.00,8.0,94103.0,736566,736566,736566,736566
35,8,1.00,5.0,94115.0,736566,736566,736566,736566
36,8,1.00,8.0,94114.0,736569,736569,736569,736569
...,...,...,...,...,...,...,...,...
198858,8,0.00,2.0,94115.0,736748,736748,736748,736748
198861,8,1.00,3.0,94108.0,736748,736748,736748,736748
198863,8,45000.00,5.0,94117.0,736748,736748,736748,736748
198865,8,1.00,2.0,94118.0,736748,736748,736748,736748
198867,8,1.00,10.0,94107.0,736748,736748,736748,736748
198868,8,1.00,9.0,94110.0,736748,736748,736748,736748
198869,8,1.00,2.0,94109.0,736748,736748,736748,736748
198870,8,1.00,2.0,94109.0,736748,736748,736748,736748
198871,8,1.00,5.0,94117.0,736748,736748,736748,736748
198873,8,1.00,9.0,94110.0,736748,736748,736748,736748
198874,8,15000.00,8.0,94131.0,736748,736748,736748,736748
198876,8,0.00,5.0,94117.0,736748,736748,736748,736748
198877,8,1000.00,11.0,94112.0,736748,736748,736748,736748
198879,8,18453.12,11.0,94112.0,736748,736748,736748,736748
198880,8,1.00,7.0,94122.0,736748,736748,736748,736748
198881,8,1.00,3.0,94133.0,736748,736748,736748,736748
198882,8,1.00,11.0,94112.0,736748,736748,736748,736748
198883,8,1.00,3.0,94102.0,736748,736748,736748,736748
198887,8,30000.00,NaN,NaN,736606,736669,736606,736636
198888,8,30000.00,NaN,NaN,736613,736670,736613,736614
198889,8,20000.00,NaN,NaN,736626,736668,736626,736626
198891,8,1.00,NaN,NaN,736660,736671,736660,736671
198892,8,38000.00,NaN,NaN,736667,736710,736667,736710
198893,8,2800.00,NaN,NaN,736668,736716,736668,736668
198894,8,7400.00,NaN,NaN,736668,736668,736668,736668
198895,8,1.00,NaN,NaN,736668,736668,736668,736668
198896,8,5000.00,NaN,NaN,736668,736669,736668,736669
198897,8,1.00,NaN,NaN,736669,736669,736669,736669
198898,8,1.00,NaN,NaN,736669,736669,736669,736669
198899,8,1.00,NaN,NaN,736670,736670,736670,736670

In [120]:
df6=pd.concat([df5, status], axis=1)

In [121]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 195142 entries, 0 to 198899
Data columns (total 9 columns):
Permit Type               180618 non-null float64
Revised Cost              180609 non-null float64
Supervisor District       178981 non-null float64
Zipcode                   178982 non-null float64
Permit Creation Date66    180618 non-null float64
Current Status Date66     180618 non-null float64
Filed Date66              180618 non-null float64
Issued Date66             180618 non-null float64
Current Status            180618 non-null float64
dtypes: float64(9)
memory usage: 14.9 MB

In [124]:
df7 = df6[pd.notnull(df6['Zipcode'])]

In [126]:
df7 = df7[pd.notnull(df7['Current Status'])]

In [128]:
df7 = df7[pd.notnull(df7['Revised Cost'])]

In [130]:
df7 = df7[pd.notnull(df7['Supervisor District'])]

In [131]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 164513 entries, 1 to 180617
Data columns (total 9 columns):
Permit Type               164513 non-null float64
Revised Cost              164513 non-null float64
Supervisor District       164513 non-null float64
Zipcode                   164513 non-null float64
Permit Creation Date66    164513 non-null float64
Current Status Date66     164513 non-null float64
Filed Date66              164513 non-null float64
Issued Date66             164513 non-null float64
Current Status            164513 non-null float64
dtypes: float64(9)
memory usage: 12.6 MB

In [134]:
df_x=df7[['Permit Type','Permit Creation Date66','Current Status','Current Status Date66','Filed Date66','Zipcode','Revised Cost','Supervisor District']].copy()
df_y=df7['Issued Date66']

In [135]:
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [136]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131610 entries, 79552 to 124952
Data columns (total 8 columns):
Permit Type               131610 non-null float64
Permit Creation Date66    131610 non-null float64
Current Status            131610 non-null float64
Current Status Date66     131610 non-null float64
Filed Date66              131610 non-null float64
Zipcode                   131610 non-null float64
Revised Cost              131610 non-null float64
Supervisor District       131610 non-null float64
dtypes: float64(8)
memory usage: 9.0 MB

In [137]:
#x_train['Neighborhoods - Analysis Boundaries'] = x_train['Neighborhoods - Analysis Boundaries'].astype('String')

In [138]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [139]:
reg.coef_

array([ -3.45109099e+01,   2.21474544e-01,   6.77024984e-01,
         1.70790271e-01,   6.16455381e-01,  -4.37646746e-02,
         5.55085891e-07,   1.89346281e-01])

In [140]:
a=reg.predict(x_test)

In [141]:
a

array([ 735999.04358069,  735180.66191687,  735424.08445386, ...,
        735199.37249762,  735486.12604276,  736548.66050671])

In [142]:
y_test

113717    736002.0
31742     735192.0
53974     735422.0
132354    736207.0
138810    736249.0
21368     735092.0
97614     735844.0
12326     735001.0
98677     735855.0
134112    736195.0
168723    736557.0
68844     735584.0
153284    736493.0
154910    736438.0
55519     735436.0
118140    736138.0
172978    736097.0
95573     735836.0
91397     735807.0
130764    736327.0
160844    736640.0
147041    736352.0
51658     735407.0
168357    735354.0
82032     735698.0
104766    735906.0
152084    736403.0
126532    736131.0
1879      734884.0
176367    736569.0
            ...
158213    736480.0
41000     735298.0
52532     735512.0
45759     735346.0
91098     735785.0
90021     735806.0
30823     735191.0
153632    736423.0
140316    736278.0
149071    736381.0
74872     735635.0
100537    736052.0
19308     735074.0
170867    736655.0
35692     735240.0
29725     735178.0
94779     736117.0
84917     735726.0
113012    735995.0
165636    736711.0
141433    736328.0
21911     735108.0
972       734876.0
115683    736019.0
153873    736424.0
71597     735600.0
103015    735907.0
33038     735219.0
61449     735494.0
167845    736549.0
Name: Issued Date66, Length: 32903, dtype: float64